# Generated by Django 3.2.7 on 2021-10-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kite_runner', '0004_profile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='favorited_by', to='kite_runner.Article'),
        ),
    ]
